include:
  - ./ops/dev/observability/docker-compose.yml

services:
  postgres:
    image: postgres:latest
    container_name: chatdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: chatpassword!
    volumes:
      - chat_db_data:/var/lib/postgresql/data
      - ./src/ChatDatabase/init-scripts:/docker-entrypoint-initdb.d

  cache:
    image: redis:latest
    ports: 
      - "6379:6379"

volumes:
  chat_db_data:
