{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traces - Zipkin",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "2a90b7d47acae32cf54ce536e143dd8f"
    }
   ]
  },
  {
   "title": "Logs - Loki",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ChatApi\"} |= ``"
    }
   ]
  },
  {
   "title": "Active Requests - Prometheus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}