version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: chat-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/caleb/chatdata/data:/var/lib/postgresql/data
      - ../src/ChatDatabase/init-scripts:/docker-entrypoint-initdb.d
    restart: always

  chat:
    container_name: chat
    build:
      context: ../src/Chat/
      dockerfile: Chat.Web/Chat.Web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ApiBaseAddress=https://chatabit.duckdns.org:1234
    restart: always

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=chatabit.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:1234:443
    restart: unless-stopped
