services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./config-files/otel-collector.yaml:/etc/otel-collector.yaml
    # ports:
      # - 1888:1888 # pprof extension
      # - 13133:13133 # health_check extension
      # - 55679:55679 # zpages extension
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
    depends_on:
      - zipkin
      - prometheus
      - loki


  zipkin:
    image: openzipkin/zipkin:latest
    # ports:
      # - "9412:9411"


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config-files/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:8080"
    # ports:
    #   - "8080:8080"
    environment:
      - config.file=/etc/prometheus/prometheus.yml


  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]


  grafana:
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    volumes:
      - ./config-files/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      GF_SECURITY_ADMIN_USER: Admin
      GF_SECURITY_ADMIN_PASSWORD: password
    depends_on:
      - zipkin
      - prometheus
      - loki
      - collector


