version: "3.9"

include:
  - compose.telemetry.yml

x-imageprocessing-base: &imageprocessing_base
  build:
    context: ../../src/Chat/
    dockerfile: Chat.ImageProcessing/Dockerfile
  restart: always

services:
  postgres:
    image: postgres:latest
    container_name: dc-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dc-postgres-data:/var/lib/postgresql/data
      - ../../src/ChatDatabase/init-scripts:/docker-entrypoint-initdb.d
    restart: always

  chat:
    container_name: dc-chat
    build:
      context: ../../src/Chat/
      dockerfile: Chat.Web/Chat.Web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ApiBaseAddress=https://chatabit.duckdns.org:1234
      - ChatApiOptions__ImageProcessingApiUrl=https://chatabit.duckdns.org:1234
      - ObservabilityOptions__CollectorUrl=http://collector:4317
    restart: always

  imageprocessing1:
    <<: *imageprocessing_base
    container_name: dc-imageprocessing1
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ObservabilityOptions__CollectorUrl=http://collector:4317
      - MicroServiceOptions__Redis=cache
      - MicroServiceOptions__Identifier=1
      - MicroServiceOptions__ImageDirectory=/app/images
    volumes:
      - images1:/images

  imageprocessing2:
    <<: *imageprocessing_base
    container_name: dc-imageprocessing2
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ObservabilityOptions__CollectorUrl=http://collector:4317
      - MicroServiceOptions__Redis=cache
      - MicroServiceOptions__Identifier=2
      - MicroServiceOptions__ImageDirectory=/app/images
    volumes:
      - images2:/images

  swag:
    container_name: dc-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=chatabit.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:1234:443
    restart: unless-stopped

  cache:
    container_name: dc-redis
    image: redis:latest
    restart: always

volumes:
  images1:
  images2:
