name: Deploy To Production

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/format.yml

  tests:
    needs: format
    uses: ./.github/workflows/test.yml

  check-changes:
    needs: tests
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Check for changes in specific services and other files
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            imageprocessing:
              - 'Chat.ImageProcessing/**'
            web:
              - 'Chat.Web/**'
            # Add other service filters here...
            any_other:
              - '**'
              - '!Chat.ImageProcessing/**'
              - '!Chat.Web/**'
              # Exclude other service paths here...

      - name: Set matrix for deployment
        id: set-matrix
        run: |
          matrix="{\"include\": ["
          if (${{ steps.check_changes.outputs.any_other }} == 'true') {
            matrix+="{\"service\":\"all\"},"
          } else {
            if (${{ steps.check_changes.outputs.imageprocessing }} == 'true') {
              matrix+="{\"service\":\"imageprocessing\"},"
            }
            if (${{ steps.check_changes.outputs.web }} == 'true') {
              matrix+="{\"service\":\"web\"},"
            }
            # Add other services as needed
          }
          matrix+="]}"
          echo "::set-output name=matrix::$matrix"

  deploy:
    needs: check-changes
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.check-changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy all services
        if: ${{ matrix.service == 'all' }}
        run: |
          docker-compose down
          docker-compose up -d

      - name: Deploy specific service
        if: ${{ matrix.service != 'all' }}
        run: |
          docker-compose down ${{ matrix.service }}
          docker-compose up -d ${{ matrix.service }}
