name: Deploy To Production

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/format.yml

  tests:
    needs: format
    uses: ./.github/workflows/test.yml

  check-changes:
    needs: tests
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Check for changes in specific services and other files
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            imageprocessing:
              - 'Chat.ImageProcessing/**'
            chat:
              - 'Chat.Web/**'
            # Add other service filters here...
            any_other:
              - '**'
              - '!Chat.ImageProcessing/**'
              - '!Chat.Web/**'
              # Exclude other service paths here...

      - name: Set matrix for deployment
        id: set-matrix
        run: |
          if [[ "${{ steps.check_changes.outputs.any_other }}" == "true" ]]; then
            echo "::set-output name=matrix::{\"include\":[{\"service\":\"all\"}]}"
          else
            matrix="{\"include\":["
            if [[ "${{ steps.check_changes.outputs.imageprocessing }}" == "true" ]]; then
              matrix+="{\"service\":\"imageprocessing\"},"
            fi
            if [[ "${{ steps.check_changes.outputs.web }}" == "true" ]]; then
              matrix+="{\"service\":\"chat\"},"
            fi
            # Remove trailing comma if any service has been added
            matrix=${matrix%,}
            matrix+="]}"
            echo "::set-output name=matrix::$matrix"
          fi

  deploy:
    needs: check-changes
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.check-changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy all services
        if: ${{ matrix.service == 'all' }}
        run: |
          cd ops/prod
          docker compose down
          docker compose up -d

      - name: Deploy specific service
        if: ${{ matrix.service != 'all' }}
        run: |
          cd ops/prod
          docker compose down ${{ matrix.service }}
          docker compose up -d ${{ matrix.service }}
