name: Diff Check and Redeploy

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      DUCKDNSTOKEN:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true
      POSTGRES_DB:
        required: true

jobs:
  diff-check-and-redeploy:
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: check for changes in ${{ inputs.folder }}
        id: diff_check
        run: |
          DIFF=$(git diff --name-only HEAD~1 HEAD -- ./${{ inputs.folder }})
          if [ -n "$DIFF" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: redeploy ${{ inputs.service }} service
        run: |
          if [ "${{ steps.diff_check.outputs.changed }}" = "true" ]; then
            cd ops/prod
            docker compose pull ${{ inputs.service }}
            docker compose build ${{ inputs.service }}
            docker compose down ${{ inputs.service }}
            docker compose up -d ${{ inputs.service }}
          fi