name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies and run tests
        run: |
          cd src/Chat
          docker build -t chat_tests -f Dockerfile .
          docker run -i --rm chat_tests dotnet test
