name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies and run tests
        run: |
          cd src/Chat
          docker build -t chat_tests -f Dockerfile .
          docker run -i --rm -v ${{ github.workspace }}:/work chat_tests dotnet test --logger trx || echo "Tests failed, check the logs for details."

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults.trx
